In [1]:
import numpy as np
import random
import gym
import matplotlib.pyplot as plt
import pickle

In [2]:
((1.732*1000)/25)*100

6928.0

In [9]:
1250*7

8750

In [10]:
1/14

0.07142857142857142

In [ ]:
uni_prob = 1/14
# node_request_probabilities = np.ones(14)*uni_prob + np.random.uniform(0,uni_prob*0.05, 14)

Generated perturbation on first run with seed of 9

In [ ]:
rng_np = np.random.default_rng(9)
pert = 0.5
node_request_probabilities = np.ones(14) + rng_np.uniform(-pert, pert, 14)

In [ ]:
node_request_probabilities = node_request_probabilities/np.sum(node_request_probabilities)

In [ ]:
np.sum(node_request_probabilities)

In [ ]:
node_request_probabilities

In [ ]:
pickle.dump(node_request_probabilities, open("/Users/joshnevin/RL_FOCSLab/node_req_probs/14_node_uniform_pert"+str(int(pert*100))+".pkl",'wb'))

In [37]:
non_uni = pickle.load(open("/Users/joshnevin/RL_FOCSLab/node_req_probs/14_node_uniform_pert50.pkl",'rb'))
uni = pickle.load(open("/Users/joshnevin/RL_FOCSLab/node_req_probs/14_node_uniform.pkl",'rb'))
grav = pickle.load(open("/Users/joshnevin/RL_FOCSLab/node_req_probs/nsfnet_chen_gravity.pkl",'rb'))

In [41]:
sum(grav)

1.00000001

In [42]:
sum(uni)

0.9999999999999997

In [43]:
sum(non_uni)

1.0

In [32]:
probs = np.zeros([len(uni),len(uni)])
for i in range(len(non_uni)):
    for j in range(len(non_uni)):
        if i != j:
            probs[i,j] = non_uni[i] * non_uni[j]
probs

array([[0.        , 0.00492341, 0.00690282, 0.00799402, 0.00760944,
        0.00885657, 0.0085125 , 0.00887445, 0.00329506, 0.00586472,
        0.00616317, 0.00353638, 0.00316389, 0.0083262 ],
       [0.00492341, 0.        , 0.0039637 , 0.00459028, 0.00436945,
        0.00508557, 0.004888  , 0.00509584, 0.00189207, 0.00336761,
        0.00353898, 0.00203064, 0.00181675, 0.00478103],
       [0.00690282, 0.0039637 , 0.        , 0.00643575, 0.00612614,
        0.00713017, 0.00685317, 0.00714457, 0.00265276, 0.00472151,
        0.00496179, 0.00284704, 0.00254716, 0.00670319],
       [0.00799402, 0.00459028, 0.00643575, 0.        , 0.00709456,
        0.00825731, 0.00793652, 0.00827398, 0.00307211, 0.00546789,
        0.00574615, 0.0032971 , 0.00294982, 0.00776283],
       [0.00760944, 0.00436945, 0.00612614, 0.00709456, 0.        ,
        0.00786007, 0.00755471, 0.00787594, 0.00292431, 0.00520484,
        0.00546972, 0.00313849, 0.00280791, 0.00738938],
       [0.00885657, 0.00508557, 0.0

In [34]:
probs = np.zeros([len(uni),len(uni)])
for i in range(len(non_uni)):
    for j in range(len(non_uni)):
        if i != j:
            probs[i,j] = uni[i] * uni[j]
probs

array([[0.        , 0.00510204, 0.00510204, 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204],
       [0.00510204, 0.        , 0.00510204, 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204],
       [0.00510204, 0.00510204, 0.        , 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204],
       [0.00510204, 0.00510204, 0.00510204, 0.        , 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204],
       [0.00510204, 0.00510204, 0.00510204, 0.00510204, 0.        ,
        0.00510204, 0.00510204, 0.00510204, 0.00510204, 0.00510204,
        0.00510204, 0.00510204, 0.00510204, 0.00510204],
       [0.00510204, 0.00510204, 0.0

In [44]:
probs = np.zeros([len(uni),len(uni)])
for i in range(len(non_uni)):
    for j in range(len(non_uni)):
        if i != j:
            probs[i,j] = grav[i] * grav[j]
probs

array([[0.        , 0.00072144, 0.00095591, 0.00034269, 0.00081162,
        0.00043287, 0.00120842, 0.00160521, 0.00248898, 0.0022004 ,
        0.00137074, 0.00216433, 0.00034269, 0.00304809],
       [0.00072144, 0.        , 0.00212425, 0.00076152, 0.00180361,
        0.00096192, 0.00268537, 0.00356713, 0.00553106, 0.00488977,
        0.00304609, 0.00480961, 0.00076152, 0.00677354],
       [0.00095591, 0.00212425, 0.        , 0.00100902, 0.00238978,
        0.00127455, 0.00355811, 0.00472645, 0.00732865, 0.00647895,
        0.00403607, 0.00637274, 0.00100902, 0.00897494],
       [0.00034269, 0.00076152, 0.00100902, 0.        , 0.00085671,
        0.00045691, 0.00127555, 0.00169439, 0.00262725, 0.00232264,
        0.00144689, 0.00228457, 0.00036172, 0.00321743],
       [0.00081162, 0.00180361, 0.00238978, 0.00085671, 0.        ,
        0.00108216, 0.00302104, 0.00401302, 0.00622244, 0.005501  ,
        0.00342685, 0.00541082, 0.00085671, 0.00762023],
       [0.00043287, 0.00096192, 0.0

In [45]:
probs = 0
for i in range(len(non_uni)):
    for j in range(len(non_uni)):
        if i != j:
            probs += grav[i] * grav[j]
probs

0.8966624467209545